name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Pull latest changes from gh-pages
        run: |
          git config user.email "t2glma00@students.oamk.fi"
          git config user.name "maguitaria"
          git config pull.rebase true  # Set Git pull strategy to merge
          git checkout -B gh-pages
          git pull origin gh-pages --allow-unrelated-histories
            git push --set-upstream origin gh-pages

      - name: Deploy to gh-pages
        run: |
          # Add necessary steps for deployment
          # Ensure you correctly build your project before deploying
           npm run deploy

          # Then, push the built files to the gh-pages branch
          git push origin gh-pages
