name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config user.email "t2glma00@students.oamk.fi"
          git config user.name "maguitaria"
          git checkout gh-pages
          rm -rf ./*
          mv -f build/* ./
          git add .
          git commit -m "Deploy latest build to gh-pages"
          git push 
